# TCL File Generated by Component Editor 12.0
# Thu Aug 16 16:22:36 EDT 2012
# DO NOT MODIFY


# 
# TLDA_peripheral "TLDA_peripheral" v1.0
# null 2012.08.16.16:22:36
# 
# 

# 
# request TCL package from ACDS 12.0
# 
package require -exact qsys 12.0


# 
# module TLDA_peripheral
# 
set_module_property NAME TLDA_peripheral
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME TLDA_peripheral
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL TLDA_peripheral
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file TLDA_peripheral.v VERILOG PATH TLDA_peripheral.v
add_fileset_file TLDA_circuit.v VERILOG PATH TLDA_circuit.v
add_fileset_file TLDA_master_interface.v VERILOG PATH TLDA_master_interface.v
add_fileset_file TLDA_slave_interface.v VERILOG PATH TLDA_slave_interface.v

add_fileset sim_verilog SIM_VERILOG "" "Verilog Simulation"
set_fileset_property sim_verilog TOP_LEVEL TLDA_peripheral
set_fileset_property sim_verilog ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file TLDA_peripheral.v VERILOG PATH TLDA_peripheral.v
add_fileset_file TLDA_circuit.v VERILOG PATH TLDA_circuit.v
add_fileset_file TLDA_master_interface.v VERILOG PATH TLDA_master_interface.v
add_fileset_file TLDA_slave_interface.v VERILOG PATH TLDA_slave_interface.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clockreset
# 
add_interface clockreset clock end
set_interface_property clockreset clockRate 0
set_interface_property clockreset ENABLED true

add_interface_port clockreset csi_clockreset_clk clk Input 1


# 
# connection point clockreset_reset
# 
add_interface clockreset_reset reset end
set_interface_property clockreset_reset associatedClock clockreset
set_interface_property clockreset_reset synchronousEdges DEASSERT
set_interface_property clockreset_reset ENABLED true

add_interface_port clockreset_reset csi_clockreset_resetn reset_n Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressAlignment DYNAMIC
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clockreset
set_interface_property slave associatedReset clockreset_reset
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave isMemoryDevice false
set_interface_property slave isNonVolatileStorage false
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave printableDevice false
set_interface_property slave readLatency 0
set_interface_property slave readWaitStates 0
set_interface_property slave readWaitTime 0
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true

add_interface_port slave avs_slave_chipselect chipselect Input 1
add_interface_port slave avs_slave_address address Input 3
add_interface_port slave avs_slave_read read Input 1
add_interface_port slave avs_slave_write write Input 1
add_interface_port slave avs_slave_writedata writedata Input 32
add_interface_port slave avs_slave_readdata readdata Output 32


# 
# connection point master
# 
add_interface master avalon start
set_interface_property master addressUnits SYMBOLS
set_interface_property master associatedClock clockreset
set_interface_property master associatedReset clockreset_reset
set_interface_property master burstOnBurstBoundariesOnly false
set_interface_property master doStreamReads false
set_interface_property master doStreamWrites false
set_interface_property master linewrapBursts false
set_interface_property master readLatency 0
set_interface_property master ENABLED true

add_interface_port master avm_master_waitrequest waitrequest Input 1
add_interface_port master avm_master_address address Output 32
add_interface_port master avm_master_write write Output 1
add_interface_port master avm_master_writedata writedata Output 16
add_interface_port master avm_master_byteenable byteenable Output 2